resources:
- repo: self

trigger:
- master
- ssharc-buildpackage

jobs:
- job: CredScan
  displayName: "Credential Scan"
  pool:
    vmImage: "windows-2019"
  steps:
  - task: ms-codeanalysis.vss-microsoft-security-code-analysis-devops.build-task-credscan.CredScan@2
    displayName: 'Run Credential Scanner'
    inputs:
      toolMajorVersion: V2
      suppressionsFile: './scripts/ci/credscan/CredScanSuppressions.json'
  - task: ms-codeanalysis.vss-microsoft-security-code-analysis-devops.build-task-postanalysis.PostAnalysis@1
    displayName: 'Post Analysis'
    inputs:
      AllTools: false
      BinSkim: false
      CredScan: true
      RoslynAnalyzers: false
      TSLint: false
      ToolLogsNotFoundAction: 'Standard'

- job: Build Package
  displayName: "Build Package"
  pool:
    vmImage: 'ubuntu-16.04'
  steps:
  - task: UsePythonVersion@0
    displayName: 'Use Python 3.6'
    inputs:
      versionSpec: 3.6
  - bash: |
      set -ev

      # prepare and activate virtualenv
      python -m venv env/

      chmod +x ./env/bin/activate
      source ./env/bin/activate

      # clone azure-cli
      git clone -q --single-branch -b dev https://github.com/Azure/azure-cli.git ../azure-cli

      python -m pip install -U pip
      pip install -q azdev

      azdev setup -c ../azure-cli -r ./

      azdev --version
      az --version

      azdev extension build ssh
  - powershell: dir

- job: StaticAnalysis
  displayName: "Static Analysis"
  pool:
    vmImage: 'ubuntu-16.04'
  steps:
    - task: UsePythonVersion@0
      displayName: 'Use Python 3.6'
      inputs:
        versionSpec: 3.6
    - bash: pip install wheel==0.30.0 pylint==1.9.5 flake8==3.5.0 requests
      displayName: 'Install wheel, pylint, flake8, requests'
    - bash: python scripts/ci/source_code_static_analysis.py
      displayName: "Static Analysis"