resources:
- repo: self

trigger:
  batch: true
  branches:
    include:
      - ssharc-buildpackage

jobs:
- job: BuildPackage
  displayName: "Build Package"
  pool:
    name: PowerShell1ES
  steps:
  - task: UsePythonVersion@0
    displayName: 'Use Python 3.8'
    inputs:
      versionSpec: 3.8
  - powershell: |
      Write-Verbose "Cloning az cli" -Verbose
      git clone -q --single-branch -b dev https://github.com/Azure/azure-cli.git ../azure-cli

      python -m venv env

      Write-Verbose "Activate Env" -Verbose
      env\Scripts\activate.ps1

      python -m pip install -U pip

      pip install azdev

      azdev setup -c ../azure-cli -r ./

      azdev --version
      az --version

      azdev extension build ssh
      dir
      
